### ISSUE TITLE
Create Interface Mockups

### ISSUE THREAD

**Issue by rramirez77** [rramirez77/Group2_AddressBook#12]

**Comment by Ehasanovic01** [comment]
https://lucid.app/lucidchart/42587da6-a156-43d8-81b9-4a02688a4119/edit?invitationId=inv_407b11f5-6fa4-49cf-a0eb-9edf347eace8

![mockup](https://user-images.githubusercontent.com/56908978/159423931-f4d2cdf4-f727-4185-adbd-1932417f7ca1.PNG)
